name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        name: "${{ matrix.os }}, python-${{ matrix.python-version }}"
        runs-on: ${{ matrix.os }}

        env:
            USING_COVERAGE: "3.8"

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.8", "3.9"]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Set up Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "${{ matrix.python-version }}"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install coverage tox tox-gh-actions

            - name: "Run tox targets for ${{ matrix.python-version }}"
              run: |
                  tox

            - name: "Coveralls"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  coveralls --service=github
